version: '3.8'

volumes:
  redis:
  mongodb:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passadmin123
    volumes:
      - ./.volume/mongodb:/data/db
    ports:
      - '27019:27017'

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ./.volume/redis:/data
    ports:
      - '6381:6379'

  # exports-processor:
  #   container_name: exports-processor
  #   build: 
  #     context: ./services/exports-processor
  #     dockerfile: ./Dockerfile.export-processor
  #   restart: always
  #   environment:
  #     - REDIS_PORT=6379
  #     - REDIS_HOST=redis
  #   ports:
  #     - '7000:4000'
  
  # inventory:
  #   container_name: inventory
  #   build: 
  #     context: ./services/inventory
  #     dockerfile: ./Dockerfile.inventory
  #   restart: always
  #   environment:
  #     - REDIS_PORT=6379
  #     - REDIS_HOST=redis
  #   ports:
  #     - '7001:4001'